package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
)

// FindBoardByID resolves a Board entity referenced by another subgraph via @key.
func (r *entityResolver) FindBoardByID(ctx context.Context, id string) (*Board, error) {
	b, err := r.Reg.GetBoard(ctx, id)
	if err != nil || b == nil {
		return nil, err
	}
	return toBoard(*b), nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
