// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

// Draw's subgraph: the cold-path control plane.
//
// This is a federation subgraph: `Board` is an entity (note @key), so a future
// supergraph router can reference a Draw board from other subgraphs by id and
// stitch in fields each subgraph owns. The live drawing does NOT live here; that
// stays on the raw WebSocket hot path. GraphQL is only for the rare, typed calls:
// list boards, look one up, create one.
type Board struct {
	// URL-safe id; open the board at /?board=<id>.
	ID    string `json:"id"`
	Title string `json:"title"`
	// Distinct objects ever added, a rough size for the board.
	ObjectCount int `json:"objectCount"`
	// RFC3339; null if nothing has been drawn yet.
	LastActiveAt *string `json:"lastActiveAt,omitempty"`
	CreatedAt    string  `json:"createdAt"`
}

func (Board) IsEntity() {}

type Mutation struct {
}

type Query struct {
}
