package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"
	"strings"
)

// CreateBoard is the resolver for the createBoard field.
func (r *mutationResolver) CreateBoard(ctx context.Context, title string) (*Board, error) {
	if strings.TrimSpace(title) == "" {
		return nil, fmt.Errorf("title is required")
	}
	b, err := r.Reg.CreateBoard(ctx, title)
	if err != nil {
		return nil, err
	}
	return toBoard(b), nil
}

// DeleteBoard is the resolver for the deleteBoard field.
func (r *mutationResolver) DeleteBoard(ctx context.Context, id string) (bool, error) {
	if err := r.Reg.DeleteBoard(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// Boards is the resolver for the boards field.
func (r *queryResolver) Boards(ctx context.Context) ([]*Board, error) {
	bs, err := r.Reg.ListBoards(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*Board, len(bs))
	for i, b := range bs {
		out[i] = toBoard(b)
	}
	return out, nil
}

// Board is the resolver for the board field.
func (r *queryResolver) Board(ctx context.Context, id string) (*Board, error) {
	b, err := r.Reg.GetBoard(ctx, id)
	if err != nil || b == nil {
		return nil, err
	}
	return toBoard(*b), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
